"""End-to-end RAG pipeline.

    upload -> parse -> clean -> chunk -> embed -> index -> retrieve -> answer

Every stage records what it produced so the RAG Test Lab can display real
numbers (chunk counts, embedding dimensions, per-chunk relevance) instead of
placeholders. Answers are generated by the configured LLM when one is
available, and otherwise by a clearly-labelled extractive summariser that cites
the retrieved chunks verbatim.
"""

from __future__ import annotations

import hashlib
import time
from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, Sequence

from ..config import Settings, get_settings
from ..constants import DEFAULT_TOP_K, SUPPORTED_DOC_EXTENSIONS
from ..exceptions import EmbeddingError, IngestionError
from ..logger import get_logger
from .chunking import Chunk, chunk_document, estimate_tokens
from .embeddings import EmbeddingProvider, describe_provider, get_embedder
from .ingestion import ParsedDocument, guess_title, parse_bytes
from .retriever import RetrievedChunk, Retriever

log = get_logger("rag.pipeline")

MAX_UPLOAD_BYTES = 25 * 1024 * 1024

__all__ = [
    "IngestionReport",
    "RagAnswer",
    "RagPipeline",
    "RagResult",
]


@dataclass(slots=True)
class IngestionReport:
    """What the ingestion pipeline did, stage by stage."""

    document_id: str
    filename: str
    title: str
    status: str
    size_bytes: int = 0
    checksum: str = ""
    pages: int = 0
    char_count: int = 0
    token_estimate: int = 0
    chunk_count: int = 0
    vectors_written: int = 0
    embedder: str = ""
    embedder_dimension: int = 0
    duration_ms: float = 0.0
    stages: list[str] = field(default_factory=list)
    error: str | None = None
    metadata: dict[str, Any] = field(default_factory=dict)

    def as_dict(self) -> dict[str, Any]:
        return {
            "document_id": self.document_id,
            "filename": self.filename,
            "title": self.title,
            "status": self.status,
            "size_bytes": self.size_bytes,
            "pages": self.pages,
            "char_count": self.char_count,
            "token_estimate": self.token_estimate,
            "chunk_count": self.chunk_count,
            "vectors_written": self.vectors_written,
            "embedder": self.embedder,
            "embedder_dimension": self.embedder_dimension,
            "duration_ms": round(self.duration_ms, 1),
            "stages": self.stages,
            "error": self.error,
            "metadata": self.metadata,
        }


@dataclass(slots=True)
class RagAnswer:
    """A generated answer plus its provenance."""

    text: str
    provider: str
    model: str
    grounded: bool
    confidence: float
    note: str = ""


@dataclass(slots=True)
class RagResult:
    """Full result of a retrieval (+ optional generation) call."""

    query: str
    chunks: list[RetrievedChunk]
    answer: RagAnswer | None = None
    top_k: int = DEFAULT_TOP_K
    latency_ms: float = 0.0
    embedder: str = ""
    store_backend: str = ""
    document_id: str | None = None

    @property
    def hit_count(self) -> int:
        return len(self.chunks)

    @property
    def top_score(self) -> float:
        return max((c.score for c in self.chunks), default=0.0)

    def sources(self) -> list[dict[str, Any]]:
        return [chunk.as_source(rank) for rank, chunk in enumerate(self.chunks, start=1)]

    def as_dict(self) -> dict[str, Any]:
        return {
            "query": self.query,
            "top_k": self.top_k,
            "hit_count": self.hit_count,
            "top_score": round(self.top_score, 4),
            "latency_ms": round(self.latency_ms, 1),
            "embedder": self.embedder,
            "store_backend": self.store_backend,
            "document_id": self.document_id,
            "answer": None
            if self.answer is None
            else {
                "text": self.answer.text,
                "provider": self.answer.provider,
                "model": self.answer.model,
                "grounded": self.answer.grounded,
                "confidence": self.answer.confidence,
                "note": self.answer.note,
            },
            "sources": self.sources(),
        }


class RagPipeline:
    """Coordinates ingestion, indexing, retrieval and answer generation."""

    def __init__(
        self,
        repository: Any,
        settings: Settings | None = None,
        *,
        retriever: Retriever | None = None,
        embedder: EmbeddingProvider | None = None,
    ) -> None:
        self.settings = settings or get_settings()
        self.settings.ensure_directories()
        self.repo = repository
        self._retriever = retriever or Retriever(repository, self.settings)
        self._embedder = embedder

    @property
    def embedder(self) -> EmbeddingProvider:
        if self._embedder is None:
            self._embedder = get_embedder(self.settings)
        return self._embedder

    @property
    def retriever(self) -> Retriever:
        return self._retriever

    # ------------------------------------------------------------------ #
    # Ingestion
    # ------------------------------------------------------------------ #
    def ingest_bytes(
        self,
        data: bytes,
        filename: str,
        *,
        title: str | None = None,
        source: str = "UPLOAD",
        document_id: str | None = None,
    ) -> IngestionReport:
        """Full ingestion pipeline for uploaded bytes."""
        started = time.perf_counter()
        stages: list[str] = []

        if len(data) > MAX_UPLOAD_BYTES:
            raise IngestionError(
                f"'{filename}' is {len(data) / 1_048_576:.1f} MB; the limit is "
                f"{MAX_UPLOAD_BYTES / 1_048_576:.0f} MB."
            )

        checksum = hashlib.sha256(data).hexdigest()
        resolved_id = document_id or self.repo.create_document(
            filename=filename,
            title=title,
            content_type=_content_type(filename),
            size_bytes=len(data),
            checksum=checksum,
            source=source,
            meta={"checksum": checksum, "stages": []},
        )
        self.repo.update_document(resolved_id, status="PENDING", error=None)

        try:
            parsed = parse_bytes(data, filename)
            stages.append(f"parsed ({parsed.page_count} page unit(s), {parsed.char_count} chars)")

            cleaned = parsed.text
            if not cleaned.strip():
                raise IngestionError(f"'{filename}' produced no text after cleaning.")
            stages.append("cleaned")

            chunks = chunk_document(
                cleaned,
                chunk_size=self.settings.chunk_size,
                overlap=self.settings.chunk_overlap,
                pages=parsed.pages or None,
            )
            if not chunks:
                raise IngestionError(f"'{filename}' could not be split into retrievable chunks.")
            stages.append(f"chunked ({len(chunks)} chunk(s))")

            vectors = self.embedder.embed([c.content for c in chunks])
            stages.append(f"embedded ({getattr(self.embedder, 'dimension', vectors.shape[1])}d)")

            self._persist_chunks(resolved_id, chunks, vectors)
            stages.append("stored")

            written = self.retriever.ensure_indexed(resolved_id, rebuild=False)
            stages.append(f"indexed ({written} vector(s))")

            self.repo.update_document(
                resolved_id,
                status="INDEXED",
                chunk_count=len(chunks),
                pages=parsed.page_count,
                error=None,
            )
            report = IngestionReport(
                document_id=resolved_id,
                filename=filename,
                title=title or parsed.title or guess_title(filename, cleaned.splitlines()[:5]),
                status="INDEXED",
                size_bytes=len(data),
                checksum=checksum,
                pages=parsed.page_count,
                char_count=parsed.char_count,
                token_estimate=estimate_tokens(cleaned),
                chunk_count=len(chunks),
                vectors_written=written,
                embedder=self.embedder.name,
                embedder_dimension=int(vectors.shape[1]) if len(chunks) else 0,
                duration_ms=(time.perf_counter() - started) * 1000,
                stages=stages,
                metadata=parsed.metadata,
            )
        except (IngestionError, EmbeddingError) as exc:
            self.repo.update_document(resolved_id, status="FAILED", error=str(exc)[:500])
            report = IngestionReport(
                document_id=resolved_id,
                filename=filename,
                title=title or filename,
                status="FAILED",
                size_bytes=len(data),
                checksum=checksum,
                duration_ms=(time.perf_counter() - started) * 1000,
                stages=stages,
                error=str(exc),
            )
        except Exception as exc:  # unexpected - still record it, never crash the UI
            log.exception("Unexpected ingestion failure for %s", filename)
            self.repo.update_document(resolved_id, status="FAILED", error=str(exc)[:500])
            report = IngestionReport(
                document_id=resolved_id,
                filename=filename,
                title=title or filename,
                status="FAILED",
                size_bytes=len(data),
                checksum=checksum,
                duration_ms=(time.perf_counter() - started) * 1000,
                stages=stages,
                error=f"Unexpected error: {exc}",
            )

        self.repo.insert_system_events(
            [
                {
                    "ts": datetime.now().astimezone(),
                    "level": "INFO" if report.status == "INDEXED" else "ERROR",
                    "source": "rag",
                    "message": f"Ingestion {report.status}: {filename} ({report.chunk_count} chunks)",
                    "context": report.as_dict(),
                }
            ]
        )
        return report

    def ingest_path(self, path: str, *, source: str = "AGENT_LOG") -> IngestionReport:
        """Ingest a document from disk (agent log shipping, sample corpora)."""
        from pathlib import Path

        file_path = Path(path)
        try:
            data = file_path.read_bytes()
        except OSError as exc:
            raise IngestionError(f"Could not read {file_path.name}: {exc}") from exc
        return self.ingest_bytes(data, file_path.name, source=source)

    def _persist_chunks(self, document_id: str, chunks: Sequence[Chunk], vectors: Any) -> None:
        rows = []
        for chunk, vector in zip(chunks, vectors):
            row = chunk.as_row(document_id)
            row["embedding"] = [float(x) for x in vector]
            rows.append(row)
        self.repo.insert_chunks(rows, include_embeddings=True)

    def delete_document(self, document_id: str) -> bool:
        self.retriever.drop_document(document_id)
        return bool(self.repo.delete_document(document_id))

    # ------------------------------------------------------------------ #
    # Retrieval
    # ------------------------------------------------------------------ #
    def retrieve(
        self,
        query: str,
        *,
        top_k: int | None = None,
        document_id: str | None = None,
        min_score: float | None = None,
        persist: bool = True,
    ) -> RagResult:
        """Retrieve relevant chunks. Optionally records the query for analytics."""
        started = time.perf_counter()
        limit = max(1, int(top_k or self.settings.rag_top_k))
        chunks = self.retriever.search(
            query, top_k=limit, document_id=document_id, min_score=min_score
        )
        result = RagResult(
            query=query,
            chunks=chunks,
            top_k=limit,
            latency_ms=(time.perf_counter() - started) * 1000,
            embedder=getattr(self.embedder, "name", "unknown"),
            store_backend=self.retriever.store.name,
            document_id=document_id,
        )
        if persist:
            try:
                self.repo.insert_rag_query(
                    query=query,
                    document_id=document_id,
                    top_k=limit,
                    provider=result.embedder,
                    hit_count=result.hit_count,
                    top_score=result.top_score,
                    latency_ms=int(result.latency_ms),
                    answer=None,
                    sources=result.sources(),
                )
            except Exception as exc:  # analytics must never break retrieval
                log.warning("Could not record RAG query: %s", exc)
        return result

    def answer(
        self,
        query: str,
        *,
        top_k: int | None = None,
        document_id: str | None = None,
        use_llm: bool = True,
        persist: bool = True,
    ) -> RagResult:
        """Retrieve, then generate a grounded answer from the retrieved chunks."""
        result = self.retrieve(query, top_k=top_k, document_id=document_id, persist=False)
        if not result.chunks:
            result.answer = RagAnswer(
                text=(
                    "No indexed chunk met the relevance threshold for this question. "
                    "Upload a relevant document or lower the minimum score in Settings."
                ),
                provider="none",
                model="none",
                grounded=False,
                confidence=0.0,
                note="No sources retrieved.",
            )
        else:
            from ..ai.rag_answer import answer_from_chunks

            result.answer = answer_from_chunks(
                query=query, chunks=result.chunks, settings=self.settings, use_llm=use_llm
            )

        if persist:
            try:
                self.repo.insert_rag_query(
                    query=query,
                    document_id=document_id,
                    top_k=result.top_k,
                    provider=result.answer.provider if result.answer else result.embedder,
                    hit_count=result.hit_count,
                    top_score=result.top_score,
                    latency_ms=int(result.latency_ms),
                    answer=result.answer.text if result.answer else None,
                    sources=result.sources(),
                )
            except Exception as exc:
                log.warning("Could not record RAG query: %s", exc)
        return result

    # ------------------------------------------------------------------ #
    # Diagnostics
    # ------------------------------------------------------------------ #
    def stats(self) -> dict[str, Any]:
        documents = self.repo.list_documents()
        index = self.retriever.index_stats()
        provider = describe_provider(self.embedder)
        return {
            "documents": int(len(documents)),
            "indexed": int((documents["status"] == "INDEXED").sum()) if not documents.empty else 0,
            "failed": int((documents["status"] == "FAILED").sum()) if not documents.empty else 0,
            "total_chunks": int(documents["chunk_count"].sum()) if not documents.empty else 0,
            "total_bytes": int(documents["size_bytes"].sum()) if not documents.empty else 0,
            "chunk_size": self.settings.chunk_size,
            "chunk_overlap": self.settings.chunk_overlap,
            "top_k": self.settings.rag_top_k,
            "min_score": self.settings.rag_min_score,
            "supported_extensions": list(SUPPORTED_DOC_EXTENSIONS),
            "vector_store": index,
            "embedder": provider,
        }


def _content_type(filename: str) -> str:
    mapping = {
        ".pdf": "application/pdf",
        ".txt": "text/plain",
        ".md": "text/markdown",
        ".markdown": "text/markdown",
        ".csv": "text/csv",
        ".json": "application/json",
        ".jsonl": "application/x-ndjson",
        ".log": "text/plain",
        ".yaml": "text/yaml",
        ".yml": "text/yaml",
    }
    from pathlib import Path

    return mapping.get(Path(filename).suffix.lower(), "application/octet-stream")
