"""Grounded RAG answers.

Two paths, and the caller can always tell which one produced the text:

* **LLM path** - the retrieved chunks are pasted into a prompt that forbids
  invention, and the answer is checked for citation markers.
* **Extractive path** - no LLM configured. The answer is assembled *from the
  retrieved sentences themselves*, so it is still grounded, and it is labelled
  as extractive. This is what keeps the RAG Test Lab honest offline instead of
  showing invented text.
"""

from __future__ import annotations

import re
from typing import Any, Sequence

from ..config import Settings
from ..constants import METRIC_LABELS
from ..exceptions import LLMError
from ..logger import get_logger
from .llm import get_llm
from .prompts import rag_prompt

log = get_logger("ai.rag_answer")

__all__ = ["answer_from_chunks", "extractive_answer"]

_CITATION = re.compile(r"\[(\d+)\]")
_SENTENCE = re.compile(r"(?<=[.!?])\s+(?=[A-Z0-9])")
_STRIP = re.compile(r"^[\s\-\*\u2022\d\.\)]+")

EXTRACTIVE_PROVIDER = "local-extractive"


def answer_from_chunks(
    query: str,
    chunks: Sequence[Any],
    settings: Settings,
    *,
    use_llm: bool = True,
) -> Any:
    """Answer ``query`` from ``chunks``.

    Returns a :class:`~sentinel.rag.pipeline.RagAnswer`. Falls back to the
    extractive path when no LLM is configured, when the LLM is disabled, or
    when the request fails - the failure reason is always surfaced in ``note``.
    """
    from ..rag.pipeline import RagAnswer

    sources = _source_payloads(chunks)

    if use_llm and settings.llm_configured:
        client = get_llm(settings)
        try:
            response = client.complete(
                rag_prompt(query, sources), system=None, temperature=settings.llm_temperature
            )
            text = response.text.strip()
            if not text:
                raise LLMError("The model returned an empty response.")
            return RagAnswer(
                text=text,
                provider=response.provider,
                model=response.model,
                grounded=bool(_CITATION.search(text)),
                confidence=_confidence_from_text(text),
                note=(
                    f"Generated by {response.model} "
                    f"({response.total_tokens} tokens, {response.latency_ms:.0f} ms)."
                ),
            )
        except LLMError as exc:
            log.warning("LLM answer failed, using extractive path: %s", exc)
            fallback = extractive_answer(query, chunks)
            fallback.note = f"LLM unavailable ({exc}); answered extractively from retrieved chunks."
            return fallback

    reason = (
        "AI answering is disabled in Settings."
        if not use_llm
        else "No LLM_API_KEY configured."
        if not settings.llm_api_key
        else "AI answering is disabled in Settings."
    )
    fallback = extractive_answer(query, chunks)
    fallback.note = f"{reason} Answer built directly from the retrieved chunks."
    return fallback


def extractive_answer(query: str, chunks: Sequence[Any]) -> Any:
    """Build a grounded answer by quoting the most relevant source sentences."""
    from ..rag.pipeline import RagAnswer

    terms = _query_terms(query)
    scored: list[tuple[float, int, str]] = []
    for index, chunk in enumerate(chunks, start=1):
        content = getattr(chunk, "content", "") or ""
        for sentence in _sentences(content):
            overlap = _overlap(terms, sentence)
            if overlap <= 0:
                continue
            length_penalty = 0.6 if len(sentence) > 320 else 1.0
            scored.append((overlap * length_penalty, index, sentence))

    scored.sort(key=lambda item: (-item[0], item[1]))
    selected: list[tuple[int, str]] = []
    seen: set[str] = set()
    for score, index, sentence in scored:
        key = re.sub(r"\W+", " ", sentence.lower()).strip()[:120]
        if key in seen:
            continue
        seen.add(key)
        selected.append((index, sentence))
        if len(selected) >= 4:
            break

    if not selected:
        body = "No sentence in the retrieved chunks matched the question terms."
        return RagAnswer(
            text=(
                "**Answer**\nNo sentence in the retrieved chunks matched the "
                "question. Try different terms, or ingest a document that covers "
                "this topic.\n\n**Confidence**\nlow - nothing in the sources "
                "addressed the question."
            ),
            provider=EXTRACTIVE_PROVIDER,
            model="sentence-overlap",
            grounded=False,
            confidence=0.15,
            note="Extractive fallback found no overlapping content.",
        )

    evidence_lines = "\n".join(f"- {sentence} [{index}]" for index, sentence in selected)
    topics = _matched_topics(terms)
    headline = (
        f"Based on the retrieved sources, {', '.join(topics)} "
        "is what the documentation covers for this question."
        if topics
        else "Based on the retrieved sources:"
    )
    text = (
        f"**Answer**\n{headline}\n\n"
        f"**Key evidence**\n{evidence_lines}\n\n"
        "**Next actions**\n"
        "1. Read the cited chunks in full for the surrounding context.\n"
        "2. Compare the cited guidance with the metric values on the device.\n"
        "3. Record the outcome as an investigation so the history stays complete.\n\n"
        f"**Confidence**\nmedium - statements are quoted from sources "
        f"{sorted({i for i, _ in selected})}, not inferred."
    )
    return RagAnswer(
        text=text,
        provider=EXTRACTIVE_PROVIDER,
        model="sentence-overlap",
        grounded=True,
        confidence=0.5,
        note="Extractive answer built from retrieved chunks (no LLM call).",
    )


# --------------------------------------------------------------------------- #
# helpers
# --------------------------------------------------------------------------- #
def _source_payloads(chunks: Sequence[Any]) -> list[dict[str, Any]]:
    payloads: list[dict[str, Any]] = []
    for chunk in chunks:
        payloads.append(
            {
                "label": getattr(chunk, "source_label", ""),
                "score": float(getattr(chunk, "score", 0.0) or 0.0),
                "content": getattr(chunk, "content", "") or "",
            }
        )
    return payloads


def _query_terms(query: str) -> set[str]:
    words = re.findall(r"[a-z0-9_]+", (query or "").lower())
    stop = {
        "the", "a", "an", "is", "are", "was", "were", "of", "to", "in", "on", "for",
        "and", "or", "do", "does", "did", "how", "what", "why", "when", "should",
        "i", "we", "it", "this", "that", "be", "can", "you", "with", "at", "by",
    }
    terms = {w for w in words if len(w) > 2 and w not in stop}
    for word in list(terms):
        if word in METRIC_LABELS:
            terms.add(METRIC_LABELS[word].lower())
    return terms


def _sentences(text: str) -> list[str]:
    flattened = " ".join((text or "").split())
    if not flattened:
        return []
    parts = _SENTENCE.split(flattened)
    return [s.strip() for s in parts if len(s.strip()) > 25]


def _overlap(terms: set[str], sentence: str) -> int:
    lowered = sentence.lower()
    return sum(1 for term in terms if term in lowered)


def _matched_topics(terms: set[str]) -> list[str]:
    return [METRIC_LABELS[key] for key in METRIC_LABELS if key in terms][:3]


def _confidence_from_text(text: str) -> float:
    """Read the model's own stated confidence, defaulting to medium."""
    lowered = text.lower()
    if "**confidence**" in lowered or "confidence:" in lowered:
        tail = lowered[lowered.rfind("confidence") :][:120]
        if "high" in tail:
            return 0.85
        if "medium" in tail:
            return 0.6
        if "low" in tail:
            return 0.3
    return 0.55
